---
- name: Run show commands
  hosts: routers
  gather_facts: no
  connection: local
  tasks:
    - name: show ip int brief
      ios_command:
        commands: show ip int brief
      register: interface_data

    - name: interface output
      debug:
        var: interface_data['stdout_lines'][0]